name: CI
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'EFSeed.sln'
      - '**/CI.yml'
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'EFSeed.sln'
      - '**/CI.yml'
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Unit test
        run: dotnet test -c Release --no-build
        working-directory: tests/EFSeed.Core.UnitTests
